- name: install and run nginx
  hosts: 172.31.86.53
  become: yes # equal to -b in adhoc commands, getting root access
  tasks:
  - name: install nginx
    ansible.builtin.package:
      name: nginx
      state: latest
  - name: start nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes      
  - name: Install the latest version of Apache
    ansible.builtin.dnf:
      name: httpd
      state: latest
      
