- name: variables from inventory
  hosts: localhost
  tasks:
  - name: print infomation
    ansible.builtin.debug:
      msg: "Hi, we are learning {{Course}} from trainer {{Trainer}}, Duration is {{Duration}}"