- name: data types
  hosts: localhost
  vars:
    course: Devops with AWS #String
    Tools: #List
    - Linux
    - Shell
    - Ansible
    Experience: #Map or dictonary
      Devops: 3 #Number
      AWS: 2
      Docker: 1
    Realproject: True #Boolean
  tasks:
  - name: print variables
    ansible.builtin.debug:
      msg: "course: {{course}}, Tools covered: {{Tools}}, Experience is: {{Experience}}, Realproject is: {{Realproject}}"

